language: python

# python:
#     - 3.6

# matrix:
#   include:
#     - python: 3.6
#     - python: 3.7
#       dist: xenial
#       sudo: true
#   allow_failures:
#       - python: 3.7

# before_script:
#     - pip install -U pipenv
#     - pipenv install --dev

jobs:
  include:
    - stage: lint
      script: flake8
    - stage: test
      script: python -c "import os; print(os.stat_float_times())"

# script: echo 0
